### ISSUE TITLE
Site generation failure based on coberatura-maven-plugin

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/mojo-parent#39]
If i do a `mvn clean verify site` with the current mojo-parent for the mrm project it will fail. If i remove the `cobertura-maven-plugin` from reporting area the build run without any issue.

The following will happend:

```
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ mrm-servlet ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntryTest
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.173 sec <<< FAILURE! - in org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntryTest
testCleanArchetypeCatalogFileEntry(org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntryTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector
    at org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntryTest.testCleanArchetypeCatalogFileEntry(ArchetypeCatalogFileEntryTest.java:22)
Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector
    at org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntryTest.testCleanArchetypeCatalogFileEntry(ArchetypeCatalogFileEntryTest.java:22)

testFileSystem(org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntryTest)  Time elapsed: 0.105 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntry
    at org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntryTest.testFileSystem(ArchetypeCatalogFileEntryTest.java:35)

testParent(org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntryTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntry
    at org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntryTest.testParent(ArchetypeCatalogFileEntryTest.java:49)

testArtifactStore(org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntryTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntry
    at org.codehaus.mojo.mrm.impl.maven.ArchetypeCatalogFileEntryTest.testArtifactStore(ArchetypeCatalogFileEntryTest.java:67)

Running org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystemTest
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.006 sec <<< FAILURE! - in org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystemTest
testSnapshotArtifactRegex(org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystemTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector
    at org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystemTest.testSnapshotArtifactRegex(ArtifactStoreFileSystemTest.java:113)
Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector
    at org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystemTest.testSnapshotArtifactRegex(ArtifactStoreFileSystemTest.java:113)

testSiteXmlReleaseVersion(org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystemTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystem
    at org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystemTest.testSiteXmlReleaseVersion(ArtifactStoreFileSystemTest.java:162)

testSiteXmlSnapshotVersion(org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystemTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystem
    at org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystemTest.testSiteXmlSnapshotVersion(ArtifactStoreFileSystemTest.java:172)

testGroupMetadataRegex(org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystemTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystem
    at org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystemTest.testGroupMetadataRegex(ArtifactStoreFileSystemTest.java:44)

testArtifactRegex(org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystemTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystem
    at org.codehaus.mojo.mrm.impl.maven.ArtifactStoreFileSystemTest.testArtifactRegex(ArtifactStoreFileSystemTest.java:60)

Running org.codehaus.mojo.mrm.impl.maven.DiskArtifactStoreTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE! - in org.codehaus.mojo.mrm.impl.maven.DiskArtifactStoreTest
testArchetypeCatalog(org.codehaus.mojo.mrm.impl.maven.DiskArtifactStoreTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector
    at org.codehaus.mojo.mrm.impl.maven.DiskArtifactStoreTest.testArchetypeCatalog(DiskArtifactStoreTest.java:18)
Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector
    at org.codehaus.mojo.mrm.impl.maven.DiskArtifactStoreTest.testArchetypeCatalog(DiskArtifactStoreTest.java:18)

Running org.codehaus.mojo.mrm.impl.maven.MockArtifactStoreTest
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE! - in org.codehaus.mojo.mrm.impl.maven.MockArtifactStoreTest
testArchetypeCatalog(org.codehaus.mojo.mrm.impl.maven.MockArtifactStoreTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org.codehaus.mojo.mrm.api.maven.BaseArtifactStore
    at org.codehaus.mojo.mrm.impl.maven.MockArtifactStoreTest.testArchetypeCatalog(MockArtifactStoreTest.java:47)

testInheritGavFromParent(org.codehaus.mojo.mrm.impl.maven.MockArtifactStoreTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org.codehaus.mojo.mrm.api.maven.BaseArtifactStore
    at org.codehaus.mojo.mrm.impl.maven.MockArtifactStoreTest.testInheritGavFromParent(MockArtifactStoreTest.java:24)

testClassifiers(org.codehaus.mojo.mrm.impl.maven.MockArtifactStoreTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org.codehaus.mojo.mrm.api.maven.BaseArtifactStore
    at org.codehaus.mojo.mrm.impl.maven.MockArtifactStoreTest.testClassifiers(MockArtifactStoreTest.java:32)


Results :

Tests in error:
  ArchetypeCatalogFileEntryTest.testArtifactStore:67 NoClassDefFound Could not i...
  ArchetypeCatalogFileEntryTest.testCleanArchetypeCatalogFileEntry:22 » NoClassDefFound
  ArchetypeCatalogFileEntryTest.testFileSystem:35 NoClassDefFound Could not init...
  ArchetypeCatalogFileEntryTest.testParent:49 NoClassDefFound Could not initiali...
  ArtifactStoreFileSystemTest.testArtifactRegex:60 NoClassDefFound Could not ini...
  ArtifactStoreFileSystemTest.testGroupMetadataRegex:44 NoClassDefFound Could no...
  ArtifactStoreFileSystemTest.testSiteXmlReleaseVersion:162 NoClassDefFound Coul...
  ArtifactStoreFileSystemTest.testSiteXmlSnapshotVersion:172 NoClassDefFound Cou...
  ArtifactStoreFileSystemTest.testSnapshotArtifactRegex:113 » NoClassDefFound ne...
  DiskArtifactStoreTest.testArchetypeCatalog:18 » NoClassDefFound net/sourceforg...
  MockArtifactStoreTest.testArchetypeCatalog:47 NoClassDefFound org.codehaus.moj...
  MockArtifactStoreTest.testClassifiers:32 NoClassDefFound org.codehaus.mojo.mrm...
  MockArtifactStoreTest.testInheritGavFromParent:24 NoClassDefFound org.codehaus...

Tests run: 13, Failures: 0, Errors: 13, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Mock Repository Manager: Project .................. SUCCESS [8.725s]
[INFO] Mock Repository Manager: API ...................... SUCCESS [17.160s]
[INFO] Mock Repository Manager: Servlet .................. FAILURE [1.596s]
[INFO] Mock Repository Manager: Web Application .......... SKIPPED
[INFO] Mock Repository Manager: Maven Plugin ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.836s
[INFO] Finished at: Wed Jul 13 17:47:10 CEST 2016
[INFO] Final Memory: 84M/1026M
```

**Comment by slachiewicz** [comment]
Tested latest mrm snapshot and mvn clean verify site runs ok

**Comment by lennartj** [comment]
The JavaNCSS part of Cobertura supports Java 7, and not Java 8 or 9 constructs.
I suggest we move over to the now-opensourced Clover instead.

Clover does not AFAIK support java 9, but at least it supports Java 8.
That in itself is a big advantage compared to Cobertura.

**Comment by andham** [comment]
I've added openjdk11 to the travis ci build and it now shows this problem with cobertura by failing all opendjk 11 builds.

**Comment by andham** [comment]
#79 removes the cobertura-m-p so I'm closing this.
