### ISSUE TITLE
Improve diagnostics when encountering a class that ASM cannot read

### ISSUE THREAD

**Issue by wilkinsona** [mojohaus/mojo-parent#43]
I recently ran Animal Sniffer's Maven plugin against a project that depends on Jersey 2.25 and it failed with an `IllegalArgumentException`. Running the build with `-X` showed that it was failing in ASM:

```
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.codehaus.mojo.animal_sniffer.ClassListBuilder.process(ClassListBuilder.java:71)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processJarFile(ClassFileVisitor.java:153)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:105)
	at org.codehaus.mojo.animal_sniffer.maven.CheckSignatureMojo.apply(CheckSignatureMojo.java:377)
	at org.codehaus.mojo.animal_sniffer.maven.CheckSignatureMojo.buildPackageList(CheckSignatureMojo.java:324)
	at org.codehaus.mojo.animal_sniffer.maven.CheckSignatureMojo.execute(CheckSignatureMojo.java:227)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

Attaching a debugger and breaking on the construction of an `IllegalArgumentException` allowed me to identify that the problematic class was `/Users/awilkinson/.m2/repository/org/glassfish/hk2/external/asm-all-repackaged/2.5.0-b30/asm-all-repackaged-2.5.0-b30.jar:module-info.class`. At this point I figured out that this class was compiled with Java 9 which ASM 5 cannot read and that I could avoid the problem by adding an `<excludeDependency>` for the offending jar.

Could the diagnostics in `ClassListBuilder` be improved so that it catches any exception that comes from ASM and logs the name of the class file that it was trying to read?

**Comment by andham** [comment]
You need to file this issue in the issue tracker of the Animal Sniffer Maven Plugin:
https://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/issue-tracking.html
